name: Deploy to Itch.io
on:
  release:
    types: [published]

jobs:
  deploy-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Windows artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: export.yml
          workflow_conclusion: success
          name: ${{ secrets.ITCHIO_GAME }}-windows
          path: build/windows
      - name: Upload to Itch.io
        uses: manleydev/butler-publish-itchio-action@v1
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: build/windows
  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Linux artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: export.yml
          workflow_conclusion: success
          name: ${{ secrets.ITCHIO_GAME }}-linux
          path: build/linux
      - name: Upload to Itch.io
        uses: manleydev/butler-publish-itchio-action@v1
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: build/linux
  deploy-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download macOS artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: export.yml
          workflow_conclusion: success
          name: ${{ secrets.ITCHIO_GAME }}-macos
          path: build/macos
      - name: Upload to Itch.io
        uses: manleydev/butler-publish-itchio-action@v1
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: osx
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: build/macos
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Web artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: export.yml
          workflow_conclusion: success
          name: ${{ secrets.ITCHIO_GAME }}-web
          path: build/web
      - name: Upload to Itch.io
        uses: manleydev/butler-publish-itchio-action@v1
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html5
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: build/web
      