name: Export and Publish

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: main

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export game
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Export
        id: export
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*