name: Export and Publish
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: main
jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export game
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Export
        id: export
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ steps.export.outputs.archive_directory }}/*
      - name: Unzip Web artifact
        run: unzip ${{ steps.export.outputs.archive_directory }}/Web.zip -d web
      - name: Enable COEP/COOP headers
        run: |
          curl https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.min.js -o web/coi-serviceworker.js
          echo '<script src="coi-serviceworker.js"></script>' >> web/index.html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: github-pages
          path: web
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
  deploy-pages:
    needs: export_game
    permissions: write-all
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          path: github-pages
      - name: Debug ls
        run: ls -l github-pages
      - name: Upload Pages artifact
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: github-pages
  deploy-itch:
    needs: export_game
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ./
      - name: Deploy Windows build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: Windows Desktop.zip
      - name: Deploy Linux build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: LinuxX11.zip
      - name: Deploy macOS build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: macOS.zip
      - name: Deploy web build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: Web.zip